// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDSyXyKaAB29BqhFjv0iPgWI55o9vDVi4',
    appId: '1:539814694384:web:18c35e3e7f1d88b2fbe135',
    messagingSenderId: '539814694384',
    projectId: 'expensesplit-pro-9e1c8',
    authDomain: 'expensesplit-pro-9e1c8.firebaseapp.com',
    storageBucket: 'expensesplit-pro-9e1c8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnlKEMvIWstNXrfAq1VufS_kaixPXYprA',
    appId: '1:539814694384:android:6bec9235c978b5f4fbe135',
    messagingSenderId: '539814694384',
    projectId: 'expensesplit-pro-9e1c8',
    storageBucket: 'expensesplit-pro-9e1c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVdfa2HJFyGUPDi1Z1GJGDDd1Rf3Zw7YQ',
    appId: '1:539814694384:ios:d32386feca488a8ffbe135',
    messagingSenderId: '539814694384',
    projectId: 'expensesplit-pro-9e1c8',
    storageBucket: 'expensesplit-pro-9e1c8.firebasestorage.app',
    iosBundleId: 'com.example.expensesplitPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVdfa2HJFyGUPDi1Z1GJGDDd1Rf3Zw7YQ',
    appId: '1:539814694384:ios:d32386feca488a8ffbe135',
    messagingSenderId: '539814694384',
    projectId: 'expensesplit-pro-9e1c8',
    storageBucket: 'expensesplit-pro-9e1c8.firebasestorage.app',
    iosBundleId: 'com.example.expensesplitPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDSyXyKaAB29BqhFjv0iPgWI55o9vDVi4',
    appId: '1:539814694384:web:a1f0bf602e22e01bfbe135',
    messagingSenderId: '539814694384',
    projectId: 'expensesplit-pro-9e1c8',
    authDomain: 'expensesplit-pro-9e1c8.firebaseapp.com',
    storageBucket: 'expensesplit-pro-9e1c8.firebasestorage.app',
  );

}